version: '3.8'

services:
  # Servicio de IA
  ai-chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=documents
      - QDRANT_VECTOR_SIZE=1536
    depends_on:
      - redis
      - qdrant
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - ai-network

  # Servicio de Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ai-network
    command: redis-server --appendonly yes

  # Servicio de Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - ai-network
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

volumes:
  redis_data:
  qdrant_data:

networks:
  ai-network:
    driver: bridge 